swagger: "2.0"
info:
  version: "v1"
  title: Please login first

host: g2jow408gmh6g20xh584g3lq0h68uyin.oastify.com

paths:

  /{Username}/{Password}:
    post:
      summary: Logs in
      parameters:
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
